baseURL: https://unitrans.ucdavis.edu/proposed-changes/
relativeURLs: true
languageCode: en-us
title: Unitrans Service Changes
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: Unitrans Service Changes. View what services changes will occur.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: unitrans.png
    link: https://unitrans.ucdavis.edu/
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Manage. Deploy.
    # Hero subtitle (optional)
    subtitle: Lorem ipsum sit dolor amet is dummy text used by the typography industry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Return to Unitrans
    url: https://unitrans.ucdavis.edu/
  - title: En español
    url: pdf/Unitrans-Service-Changes-Spanish.pdf
  - title: 用中文
    url: pdf/Unitrans-Service-Changes-Chinese.pdf
  section2:
    title: UNITRANS 2020-2021 SERVICE CHANGE PROPOSALS
    title2: RELIABILITY IMPROVEMENTS
    subtitle: Unitrans is proposing the following changes to bus service to take effect in August 3, 2020 for the 2020-21 academic year. Proposals focus on improving your ride by making it faster and more reliable. For more information on each proposal, go to unitrans.ucdavis.edu. To comment, email comments@unitrans.ucdavis.edu, call 530-752-2877, or mail Unitrans, 1 Shields Avenue, 5 South Hall, Davis, CA 95616. The comment period will close on Friday, May 22, 2020.
    leftCol:
    - title: All Door Boarding Pilot
      bullets:
        - text: Customers with passes will be allowed to board through any door to decrease boarding times. Only cash payers and 10-ride ticket holders will be required to board through the front doors. We trust our valued customers to continue to pay for their trips. As a reminder, Unitrans already entrusts customers at the Silo and Memorial Union Bus Terminals to pay their fare. Unitrans is not free at terminals. Pilot will last for up to a year.  
    - title: Morning Schedule Update on All Lines
      bullets:
        - text: All morning schedules will shift five minutes earlier between 6:30 AM and 9:00 AM to provide extra time for 9:00 AM arrivals. No changes to campus departures after 9:00 AM.
        - text: "<a target='_blank' href='pdf/SampleMorningSchedules.pdf'>Click here for sample schedules</a>"
    - image: clock1.png
    - title: "Drop Off Only Stop Pilot on the G, J, and V Lines:"
      bullets:
        - text: To improve travel times, Unitrans proposes drop off only stops at outbound (away from campus) bus stops on Alvarado Avenue and Sycamore Lane for the G/J lines and on Hutchison Drive at Sage Street and Sage Street at West Village Square on the V line. Customers will not be allowed to board at drop off only stops.
        - text: "<a target='_blank' href='https://drive.google.com/open?id=1uarU6Bn1pD4BbLA1DtgX2FcCnsd5youU&usp=sharing'>Click here for G/J Line Impacted Stops</a>"
        - text: "<a target='_blank' href='https://drive.google.com/open?id=1sfdcRAp54x05em1Q-Lz5ugM35cVtT2Sa&usp=sharing'>Click here for V Line Impacted Stops</a>"
    - image: drop_off.png
    rightCol:
    - image: bus_image.png
    - title: Afternoon Schedule Update on V Line
      bullets:
        - text: Unitrans proposes adjusting the 25 minute after the hour afternoon and evening Silo Terminal V Line departures to 20 minutes after the hour to better meet customer demand.
        - text: "<a target='_blank' href='pdf/V_Line_Sample.pdf'>Click here for sample schedules</a>"
    - image: clock2.png
    - heading: CAPACITY FOCUSED IMPROVEMENTS
      # Icon (from /images/illustrations/icons/___.svg)
    - title: "Unitrans proposes:"
      bullets:
        - text: Increased weekday morning capacity trips on the A and V lines.
        - text: New 7:10 PM Z line and 8:10 PM K and Z line trips
        - text: Elimination of 6:20 PM D, G, J, and W lines and 6:25 PM V line trips. Buses will be used on overcrowded and late 6:35 PM trips
    - image: bus_symbols.png
    - heading: REMINDER FROM 2019
    - title: A/O/Z Line Westbound Reroute Near the Davis Amtrak Station
      bullets:
        - text: As approved in April 2019, Unitrans will implement the approved A/O/Z line westbound reroute near the Davis Amtrak Station if safety incidents increase.
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
